### ISSUE TITLE
Api for collaborators is case sensitive

### ISSUE THREAD

**Issue by Magehernan** [drips-network/multiplayer#10]
Hi, i am participating in a round and i see that a address was in whitelist but if you check the same address with uppercases it was saying that it was not, so i leave urls that is espected that return the same value but returns different values.

https://www.drips.network/api/multiplayer/votingRounds/0270e337-047d-46a0-a55a-99d6030c285e/collaborators/0x99DA4128e3Fdb67A3dFFc304333dE663BD5a8D8C

https://www.drips.network/api/multiplayer/votingRounds/0270e337-047d-46a0-a55a-99d6030c285e/collaborators/0x99da4128e3fdb67a3dffc304333de663bd5a8d8c

the two address are the same address but one all lowercase... so i thing this is a bug and is preventing this address to vote.

i hope it helps

If this is a security feature, then i recommend to add a check to the array of collaborators when added to inform that there are address that are invalid so this not happend.

**Comment by efstajas** [comment]
Hey @Magehernan! Thanks a lot for raising this. This service does expect to use checksummed addresses always, but our UI would usually always checksum addresses even if whoever created the voting round entered them as lowercase. The only reason this happened with your address is because the Scroll folks asked us to manually add some additional voters to the vote after the fact, which we don't support as a feature yet, so we did it manually. And while doing that, we didn't think to make sure all the addresses are checksummed.

We just made sure all addresses for that vote are checksummed, so you should be able to vote now 👌 Sorry for the inconvenience. Let me know if you still have problems.
